POST http://localhost:8000/calculator
Content-Type: text/xml

<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Body>
        <operation xmlns="http://localhost:8080/calculator">
            <x xmlns="">5</x>
            <y xmlns="">7</y>
        </operation>
    </Body>
</Envelope>